name: phone_numbers_parser
description: Dart library for parsing phone numbers. Inspired by Google's libphonenumber and PhoneNumberKit for ios.
version: 9.0.5
homepage: https://github.com/cedvdb/phone_number_parser

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.10.0

dev_dependencies:
  xml: ^6.5.0
  lints: ^3.0.0
  test: ^1.25.2
