name: phone_numbers_parser
description: Dart library for parsing phone numbers. Inspired by Google's libphonenumber and PhoneNumberKit for ios.
version: 8.0.0
homepage: https://github.com/cedvdb/phone_number_parser

environment:
  sdk: ">=3.0.0"

dependencies:
  meta: ^1.7.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.4
